### ISSUE TITLE
Implement funk.Some

### ISSUE THREAD

**Issue by thoas** [thoas/go-funk#10]

**Comment by sunnypatel165** [comment]
Elaborate please @thoas

**Comment by thoas** [comment]
inspired from [lodash some](https://lodash.com/docs/4.17.11#some)

**Comment by ZeeshanTamboli** [comment]
@thoas Can I look into this? It's open from a long time so making sure.

**Comment by thoas** [comment]
yes @ZeeshanTamboli, you can look into this, it's very welcome!
