### ISSUE TITLE
Consider add missing examples in the README

### ISSUE THREAD

**Issue by Dentrax** [thoas/go-funk#108]
Since all of the exported functions described [here](https://pkg.go.dev/github.com/thoas/go-funk) already, I think it should be better if we add some of the important ones: _(i.e. `zip`, `min`, `max`, `permutation`, `join`, and other missing functions). What do you think? 🤔

**Comment by thoas** [comment]
Hay @Dentrax, thank you for the report you can send a PR anytime!
