### ISSUE TITLE
All functions return interface{}

### ISSUE THREAD

**Issue by AlexandrosMelissas** [thoas/go-funk#137]
Hello. I'm kinda new to Golang so this may sound noobish. I've installed go-funk and even though it works great, every funk function returns interface {} instead of the type it's given.
For example: 
``` 
foundSomething := funk.Find(ourArray, func(data ourType) bool {
		return data.ID == someRandomId
	})
```
Shouldn't foundSomething variable be of type ourType and not interface{}? There must be something I'm missing here.
The workaround i've found is this but it creates more problems later: 
```
foundSomething := funk.Find(ourArray, func(data ourType) bool {
		return data.ID == someRandomId
	}).(ourType)
 ```

**Comment by thoas** [comment]
it uses `interface{}` since generics will be available from 1.18.

You can cast the result at runtime or use typesafe functions.
