### ISSUE TITLE
About GetOrElse

### ISSUE THREAD

**Issue by zhuxubin01** [thoas/go-funk#138]
I think GetOrElse's implementation should like this,in actuality,the most cases want to set default value when input is zero value

func GetOrElse(v interface{}, def interface{}) interface{} {
	if v == nil {
		return def
	}

	val := reflect.ValueOf(v)
	if val.Kind() == reflect.Ptr {
		val = val.Elem()
	}

	if val.IsZero()  {
		return def
	} else if val.Kind() != reflect.Ptr {
		return v
	}

	return val.Elem().Interface()
}

**Comment by thoas** [comment]
send a PR to review.
