### ISSUE TITLE
Generics coming into Go 1.18

### ISSUE THREAD

**Issue by samber** [thoas/go-funk#144]
I just released a `go-funk`-style package, adding support for Go 1.18+ generics.

https://github.com/samber/lo

This is a hard fork, since it brings a lot of breaking changes.

80% coverage of Lodash specs.

**Comment by thoas** [comment]
Hi @samber,

Great work, really! I was looking for time to port `go-funk` with generics (of course with breaking changes), I think it's time to flag the library `1.x` too at the same time.

If you want to integrate your hard fork into `go-funk`, I can add you as collaborator.

**Comment by thoas** [comment]
closing this issue, since `lo` will have its own path :)

Thank you for your work!
