### ISSUE TITLE
Use generics from go 1.18

### ISSUE THREAD

**Issue by GRbit** [thoas/go-funk#147]
It's 1.18 now.
Are you planning update your code to use generics? It will improve speed dramatically.

I know that some of the functions can't be properly updated due to the fact that interfaces are more flexible than generics, but there are a lot of functions that could be updated. And because of https://pkg.go.dev/golang.org/x/exp/maps and https://pkg.go.dev/golang.org/x/exp/slices some functions aren't useful right now. So, there are a lot of work =)

Will you accept any pull requests with generics?

**Comment by valiangspe** [comment]
Looking forward to this. Greatly appreciated

**Comment by andig** [comment]
I‘ve just gone through the exercise and replaced funk by generics, mainly /x/exp/slices, which proved for my uses straightforward. The main omission in Go regarding slices is missing Map/ Reduce/ Filter afaikt.

**Comment by metalrex100** [comment]
@thoas create please v2 branch so it became possible to contribute.

**Comment by thoas** [comment]
@metalrex100 I will, it will be available next week :)

**Comment by metalrex100** [comment]
@thoas is there any functions that you did not implement so far with generics?
I may provide PR's with their implementation 🙂

**Comment by andig** [comment]
Note https://github.com/golang/go/issues/45955#issuecomment-1085310560 which links https://github.com/luraim/fun

**Comment by andig** [comment]
> Instead currently everyone, who wants to use generics helpers, but would like to use it with well-known package instead of self-written implementation are blocked by maintainers of the go-funk and lo packages.

I don't feel blocked. Instead I can continue using this excellent module or move to any generics-based package including my ohne patches until something more mature comes up. Big thank you to @thoas for all his work sofar.

**Comment by metalrex100** [comment]
@andig when codebase is pretty big - it require to spend much time on replacing your self-written solutions with some well-known package.

**Comment by thoas** [comment]
> @andig when codebase is pretty big - it require to spend much time on replacing your self-written solutions with some well-known package.

Yes, it takes more time than expected I will have a first draft a the end of the week. I have created a `v2` branch, you can send me some PRs if you want.

**Comment by metalrex100** [comment]
@thoas it will be actually almost another lib. Methods names will be still the same))

**Comment by thoas** [comment]
> @thoas it will be actually almost another lib. Methods names will be still the same))

Yes, that's why it will be separated to a complete new branch and installed via gomod using `v2`. There is a lot of things to rewrite and we must focus on basic utilities first.

**Comment by metalrex100** [comment]
@thoas indeed. New implementation also must be placed in `v2` folder according to GO versioning system.

**Comment by metalrex100** [comment]
Or you want to deal with versioning by always having 2 branches instead of single master with 2 directories: root and v2?

**Comment by gopherhw** [comment]
Two weeks passed . @thoas

**Comment by thoas** [comment]
@gopherhw I know, lack of time :)

**Comment by yangxikun** [comment]
Is there any progress on this?

**Comment by GRbit** [comment]
@yangxikun to be honest, zero from my side. I switched to github.com/samber/lo

**Comment by thoas** [comment]
You can switch to [samber/lo](https://github.com/samber/lo) which is pretty complete.
