### ISSUE TITLE
Q: Is there any utility for merge

### ISSUE THREAD

**Issue by krishnaTORQUE** [thoas/go-funk#148]
Is there any utility for merge structs or map or array ?

**Comment by DerkSchooltink** [comment]
yes

**Comment by krishnaTORQUE** [comment]
Thank you @DerkSchooltink 
It will be very helpful if you share a code snippet or the utility function name.

**Comment by thoas** [comment]
you can use an utility like [mergo](https://github.com/imdario/mergo) if you are not afraid of reflect.

For a map:
```go
for k, v := range b {
    a[k] = v
}
```
