### ISSUE TITLE
reflect: call of reflect.Value.Set on zero Value

### ISSUE THREAD

**Issue by deletexl** [thoas/go-funk#152]
Hello, I am using this library in a project and sometimes I encounter the following error.

`
2022/05/08 18:09:12 reflect: call of reflect.Value.Set on zero Value
`

How can I control this error? How can I prevent it from happening?

Usage:

`
dataMutex.Lock()
allDatas := funk.Values(datas)
dataMutex.Unlock()

`

Error:

fatal error: concurrent map read and map write

thoas/go-funk@v0.9.2/map.go:55 +0x269 fp=0xc0055bfbf8 sp=0xc0055bfaf8 pc=0x723b89

map.go
		for i, key := range keys {
// 55.			resultSlice.Index(i).Set(value.MapIndex(key))
		}

**Comment by thoas** [comment]
Hi,

I need a proper example of what you are doing, could you send me a playground?

Until further notice, I will close this issue.
