### ISSUE TITLE
Typesafe / zero allocs implementation

### ISSUE THREAD

**Issue by thoas** [thoas/go-funk#21]
- [x] ContainsInt
- [x] ContainsInt64
- [x] ContainsFloat64
- [x] ContainsString
- [x] ContainsStrings
- [x] ContainsFloat32
- [x] ReverseString
- [x] ReverseInt
- [x] SumInt
- [x] SumInt64
- [x] SumFloat64
- [x] SumFloat32
- [x] UniqInt
- [x] UniqString
- [x] UniqInt64
- [x] UniqFloat32
- [x] UniqFloat64
- [x] ShuffleInt
- [x] ShuffleString
- [x] ShuffleInt64
- [x] ShuffleFloat32
- [x] ShuffleFloat64
- [x] IndexOfInt
- [x] IndexOfString
- [x] IndexOfInt64
- [x] IndexOfFloat64
- [x] LastIndexOfInt
- [x] LastIndexOfString
- [x] LastIndexOfInt64
- [x] LastIndexOfFloat64
- [x] FilterInt
- [x] FilterInt64
- [x] FilterString
- [x] FilterFloat32
- [x] FilterFloat64
- [x] FindFloat32
- [x] FindFloat64
- [x] FindString
- [x] FindInt64
- [x] FindInt

**Comment by marklr** [comment]
Do you need a hand with implementing these?

**Comment by thoas** [comment]
Hay, yes of course don't hesitate :)
