### ISSUE TITLE
Implement funk.Min

### ISSUE THREAD

**Issue by thoas** [thoas/go-funk#27]

**Comment by abshek** [comment]
@thoas Hey, may I take this one? I already have a PR for #28. I can implement this in similar fashion.

**Comment by thoas** [comment]
@abshek go for it, thank you! :)

**Comment by CatInCosmicSpace** [comment]
Hello, @thoas! I already implemented (similar to Max) in #66.

**Comment by thoas** [comment]
Thank you @CatInCosmicSpace
