### ISSUE TITLE
Implement funk.Max

### ISSUE THREAD

**Issue by thoas** [thoas/go-funk#28]

**Comment by harshilsharma63** [comment]
@thoas I'd like to get on this and #27. I wanted to clarify requirements for the two, whether we want them to give max/min out of an array of just out of two elements? Also, I suppose we'll be allowing for passing a custom comparator?

**Comment by abshek** [comment]
@thoas Hey, may I work on this? I tried to implement the following:

`Max` checks for the type of input, validates the input, compares the elements and returns the maximum element in an array/slice
- It accepts []int, []int8, []int16, []int32, []int64, []float32, []float64, []string
- It returns int or string or nil
- It returns nil for the following cases: 
          - input is not an array/slice 
          - input has heterogeneous elements
- For strings, the first different character amongst the elements is compared using go's inbuilt strings.Compare method 

Let me know if you want any additions/modifications.

**Comment by thoas** [comment]
@abshek sounds good, go for it I will review your implementation then!

Thank you :)

**Comment by thoas** [comment]
done by @abshek
