### ISSUE TITLE
Implement #Any and #All

### ISSUE THREAD

**Issue by rezam90** [thoas/go-funk#46]
Hi @thoas
have time to add #Any and #All functions?
it would be great if supports structs too.
like find out if a user in a slice has a admin field true.
thanks

**Comment by thoas** [comment]
hi @rezam90,

could you provide me an example of what you're looking for?

**Comment by rezam90** [comment]
for Any I meant something like this: [AnyFn](https://godoc.org/github.com/rezam90/go-funk#AnyFn)
