### ISSUE TITLE
Reduce must return an interface to support multiple type

### ISSUE THREAD

**Issue by kubino** [thoas/go-funk#50]
Hi I would like to use Reduce function but it seems that output result must be always float64, so no Map or Array or whatever else is supported?  I am completely new to Go maybe I am missing something. Thank you for your help.

**Comment by thoas** [comment]
You are right, it seems the `Reduce` has been done only for integer at the moment feel free to send a patch to support others operations.

**Comment by reetuparna** [comment]
Taking this up
