### ISSUE TITLE
Support for go modules and more go compliant versioning

### ISSUE THREAD

**Issue by trivigy** [thoas/go-funk#58]
This is a minor feature request. I love the library and would love to see support for go modules as well as well better versioning.

This is how the library loads within my project when I use go modules. This makes it harder to depend on stable versions of the library.
```
module github.com/syncaide/gate

require (
        ...
	github.com/thoas/go-funk v0.0.0-20190407194523-c43409e2d5de
        ...
)
```

With go.mod being added and a more golang compliant versioning scheme the dependency would end up looking as follows. This is much more dependable if in the future there are breaking changes introduced into the application.
```
module github.com/syncaide/gate

require (
        ...
	github.com/thoas/go-funk v0.4.0
        ...
)
```

**Comment by thoas** [comment]
agreed, we will be more compliant.

**Comment by thoas** [comment]
I updated tags and keep old tags for backward compatibility.

It should solve your issue, don't hesitate.
