### ISSUE TITLE
Support FindIndex function

### ISSUE THREAD

**Issue by HayTran94** [thoas/go-funk#60]
If I use `Find` function, I'll get a object. If I use `IndexOf` function, the predicate function will not work. 

So I want the lib support `FindIndex` or something like that would help me to find a object with its index. Thank you so much

**Comment by sunnypatel165** [comment]
Does it make sense to just change the ```Find``` function to return both index and the object? It might break a lot of existing code, but it makes sense to me

In any case, @thoas do you want this to be added? I'd like to get my hands dirty at it

**Comment by thoas** [comment]
We should not break existing code, you can send a PR for `FindIndex`.
