### ISSUE TITLE
Implement funk.If (short if) enhancement

### ISSUE THREAD

**Issue by leowilbur** [thoas/go-funk#86]
funk.If(condition, true, false)

**Comment by thoas** [comment]
hi @leowilbur, could you add an example for someone which wants to take the issue?

Thank you.

**Comment by stevefan1999-personal** [comment]
@thoas There's no need for that. The long time missing of ternary expression is a big problem in Golang already

**Comment by reetuparna** [comment]
Would like to work on this, if it's not already taken @thoas @stevefan1999-personal @leowilbur

**Comment by thoas** [comment]
@reetuparna you can take it! Not a big fan of ternary expression (for visibility reason) :)
