### ISSUE TITLE
Possible clarification needed for `Uniq` function?

### ISSUE THREAD

**Issue by cmaster11** [thoas/go-funk#87]
Hi! I was browsing through the code, and for the `Uniq` function I noticed this line:

https://github.com/thoas/go-funk/blob/1d24b29f494de60ee42c92cd5016a8efc3084296/transform.go#L328

Now, the code `value.Index(j).Set(val)` is actively editing the input argument. Could you help me understand why this line exists/does what it does? I'm failing to grasp the logic behind it 😅

Edit: A coffee helped. I understand the algorithm itself, it edits the input argument and a copy is therefore not needed, using `j` as a secondary index. Though, there is no mention in the comment/function doc (unless I missed it somewhere), that it actually alters the original array! Maybe this issue is more related to this, I was not understanding why the input argument was being altered.

Thanks a lot,
Alberto

**Comment by thoas** [comment]
hi @cmaster11 

I think it's a mistake it should not edit the input argument and instead returns a copy of it.
